package com.hdy.myhxc.model;

import java.util.Date;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.Menu_ID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.Menu_Name
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.Menu_URL
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.Parent_ID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.Menu_ICO
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String menuIco;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.Leavel_ID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private Integer leavelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.SORT
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.Create_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.Create_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.Update_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.Update_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.DelFg
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String delfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.Beizhu
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String beizhu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.UUID
     *
     * @return the value of m_menu.UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.UUID
     *
     * @param uuid the value for m_menu.UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.Menu_ID
     *
     * @return the value of m_menu.Menu_ID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.Menu_ID
     *
     * @param menuId the value for m_menu.Menu_ID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.Menu_Name
     *
     * @return the value of m_menu.Menu_Name
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.Menu_Name
     *
     * @param menuName the value for m_menu.Menu_Name
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.Menu_URL
     *
     * @return the value of m_menu.Menu_URL
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.Menu_URL
     *
     * @param menuUrl the value for m_menu.Menu_URL
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.Parent_ID
     *
     * @return the value of m_menu.Parent_ID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.Parent_ID
     *
     * @param parentId the value for m_menu.Parent_ID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.Menu_ICO
     *
     * @return the value of m_menu.Menu_ICO
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getMenuIco() {
        return menuIco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.Menu_ICO
     *
     * @param menuIco the value for m_menu.Menu_ICO
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setMenuIco(String menuIco) {
        this.menuIco = menuIco == null ? null : menuIco.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.Leavel_ID
     *
     * @return the value of m_menu.Leavel_ID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public Integer getLeavelId() {
        return leavelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.Leavel_ID
     *
     * @param leavelId the value for m_menu.Leavel_ID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setLeavelId(Integer leavelId) {
        this.leavelId = leavelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.SORT
     *
     * @return the value of m_menu.SORT
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.SORT
     *
     * @param sort the value for m_menu.SORT
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.Create_User
     *
     * @return the value of m_menu.Create_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.Create_User
     *
     * @param createUser the value for m_menu.Create_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.Create_Date
     *
     * @return the value of m_menu.Create_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.Create_Date
     *
     * @param createDate the value for m_menu.Create_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.Update_User
     *
     * @return the value of m_menu.Update_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.Update_User
     *
     * @param updateUser the value for m_menu.Update_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.Update_Date
     *
     * @return the value of m_menu.Update_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.Update_Date
     *
     * @param updateDate the value for m_menu.Update_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.DelFg
     *
     * @return the value of m_menu.DelFg
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getDelfg() {
        return delfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.DelFg
     *
     * @param delfg the value for m_menu.DelFg
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setDelfg(String delfg) {
        this.delfg = delfg == null ? null : delfg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.Beizhu
     *
     * @return the value of m_menu.Beizhu
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.Beizhu
     *
     * @param beizhu the value for m_menu.Beizhu
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu == null ? null : beizhu.trim();
    }
}