package com.hdy.myhxc.model;

import java.util.Date;

public class RoleAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_roleauthority.UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_roleauthority.Role_UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String roleUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_roleauthority.Menu_ID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_roleauthority.Create_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_roleauthority.Create_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_roleauthority.Update_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_roleauthority.Update_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_roleauthority.DelFg
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String delfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_roleauthority.Beizhu
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String beizhu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_roleauthority.UUID
     *
     * @return the value of m_roleauthority.UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_roleauthority.UUID
     *
     * @param uuid the value for m_roleauthority.UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_roleauthority.Role_UUID
     *
     * @return the value of m_roleauthority.Role_UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getRoleUuid() {
        return roleUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_roleauthority.Role_UUID
     *
     * @param roleUuid the value for m_roleauthority.Role_UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setRoleUuid(String roleUuid) {
        this.roleUuid = roleUuid == null ? null : roleUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_roleauthority.Menu_ID
     *
     * @return the value of m_roleauthority.Menu_ID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_roleauthority.Menu_ID
     *
     * @param menuId the value for m_roleauthority.Menu_ID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_roleauthority.Create_User
     *
     * @return the value of m_roleauthority.Create_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_roleauthority.Create_User
     *
     * @param createUser the value for m_roleauthority.Create_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_roleauthority.Create_Date
     *
     * @return the value of m_roleauthority.Create_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_roleauthority.Create_Date
     *
     * @param createDate the value for m_roleauthority.Create_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_roleauthority.Update_User
     *
     * @return the value of m_roleauthority.Update_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_roleauthority.Update_User
     *
     * @param updateUser the value for m_roleauthority.Update_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_roleauthority.Update_Date
     *
     * @return the value of m_roleauthority.Update_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_roleauthority.Update_Date
     *
     * @param updateDate the value for m_roleauthority.Update_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_roleauthority.DelFg
     *
     * @return the value of m_roleauthority.DelFg
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getDelfg() {
        return delfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_roleauthority.DelFg
     *
     * @param delfg the value for m_roleauthority.DelFg
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setDelfg(String delfg) {
        this.delfg = delfg == null ? null : delfg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_roleauthority.Beizhu
     *
     * @return the value of m_roleauthority.Beizhu
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_roleauthority.Beizhu
     *
     * @param beizhu the value for m_roleauthority.Beizhu
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu == null ? null : beizhu.trim();
    }
}