package com.hdy.myhxc.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.UUID
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.User_Code
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.User_Psd
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String userPsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.User_Dep
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String userDep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.User_DepNM
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String userDepnm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.User_NM
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String userNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.User_Gender
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String userGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.User_Tel
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String userTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.User_Role
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.Update_PWDT
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private Date updatePwdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.IsConstructionUnit
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String isconstructionunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.IsRoadPatrol
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String isroadpatrol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.IsDesignatedCU
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String isdesignatedcu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.IsEndTask
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String isendtask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.Handheld_Device
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String handheldDevice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.JGRegister_ID
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String jgregisterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.Create_User
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.Create_Date
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.Update_User
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.Update_Date
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.DelFg
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String delfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.Beizhu
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    private String beizhu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.UUID
     *
     * @return the value of m_user.UUID
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.UUID
     *
     * @param uuid the value for m_user.UUID
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.User_Code
     *
     * @return the value of m_user.User_Code
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.User_Code
     *
     * @param userCode the value for m_user.User_Code
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.User_Psd
     *
     * @return the value of m_user.User_Psd
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getUserPsd() {
        return userPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.User_Psd
     *
     * @param userPsd the value for m_user.User_Psd
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setUserPsd(String userPsd) {
        this.userPsd = userPsd == null ? null : userPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.User_Dep
     *
     * @return the value of m_user.User_Dep
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getUserDep() {
        return userDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.User_Dep
     *
     * @param userDep the value for m_user.User_Dep
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setUserDep(String userDep) {
        this.userDep = userDep == null ? null : userDep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.User_DepNM
     *
     * @return the value of m_user.User_DepNM
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getUserDepnm() {
        return userDepnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.User_DepNM
     *
     * @param userDepnm the value for m_user.User_DepNM
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setUserDepnm(String userDepnm) {
        this.userDepnm = userDepnm == null ? null : userDepnm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.User_NM
     *
     * @return the value of m_user.User_NM
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getUserNm() {
        return userNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.User_NM
     *
     * @param userNm the value for m_user.User_NM
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setUserNm(String userNm) {
        this.userNm = userNm == null ? null : userNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.User_Gender
     *
     * @return the value of m_user.User_Gender
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.User_Gender
     *
     * @param userGender the value for m_user.User_Gender
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.User_Tel
     *
     * @return the value of m_user.User_Tel
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.User_Tel
     *
     * @param userTel the value for m_user.User_Tel
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.User_Role
     *
     * @return the value of m_user.User_Role
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.User_Role
     *
     * @param userRole the value for m_user.User_Role
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole == null ? null : userRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.Update_PWDT
     *
     * @return the value of m_user.Update_PWDT
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public Date getUpdatePwdt() {
        return updatePwdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.Update_PWDT
     *
     * @param updatePwdt the value for m_user.Update_PWDT
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setUpdatePwdt(Date updatePwdt) {
        this.updatePwdt = updatePwdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.IsConstructionUnit
     *
     * @return the value of m_user.IsConstructionUnit
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getIsconstructionunit() {
        return isconstructionunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.IsConstructionUnit
     *
     * @param isconstructionunit the value for m_user.IsConstructionUnit
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setIsconstructionunit(String isconstructionunit) {
        this.isconstructionunit = isconstructionunit == null ? null : isconstructionunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.IsRoadPatrol
     *
     * @return the value of m_user.IsRoadPatrol
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getIsroadpatrol() {
        return isroadpatrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.IsRoadPatrol
     *
     * @param isroadpatrol the value for m_user.IsRoadPatrol
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setIsroadpatrol(String isroadpatrol) {
        this.isroadpatrol = isroadpatrol == null ? null : isroadpatrol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.IsDesignatedCU
     *
     * @return the value of m_user.IsDesignatedCU
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getIsdesignatedcu() {
        return isdesignatedcu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.IsDesignatedCU
     *
     * @param isdesignatedcu the value for m_user.IsDesignatedCU
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setIsdesignatedcu(String isdesignatedcu) {
        this.isdesignatedcu = isdesignatedcu == null ? null : isdesignatedcu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.IsEndTask
     *
     * @return the value of m_user.IsEndTask
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getIsendtask() {
        return isendtask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.IsEndTask
     *
     * @param isendtask the value for m_user.IsEndTask
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setIsendtask(String isendtask) {
        this.isendtask = isendtask == null ? null : isendtask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.Handheld_Device
     *
     * @return the value of m_user.Handheld_Device
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getHandheldDevice() {
        return handheldDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.Handheld_Device
     *
     * @param handheldDevice the value for m_user.Handheld_Device
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setHandheldDevice(String handheldDevice) {
        this.handheldDevice = handheldDevice == null ? null : handheldDevice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.JGRegister_ID
     *
     * @return the value of m_user.JGRegister_ID
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getJgregisterId() {
        return jgregisterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.JGRegister_ID
     *
     * @param jgregisterId the value for m_user.JGRegister_ID
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setJgregisterId(String jgregisterId) {
        this.jgregisterId = jgregisterId == null ? null : jgregisterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.Create_User
     *
     * @return the value of m_user.Create_User
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.Create_User
     *
     * @param createUser the value for m_user.Create_User
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.Create_Date
     *
     * @return the value of m_user.Create_Date
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.Create_Date
     *
     * @param createDate the value for m_user.Create_Date
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.Update_User
     *
     * @return the value of m_user.Update_User
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.Update_User
     *
     * @param updateUser the value for m_user.Update_User
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.Update_Date
     *
     * @return the value of m_user.Update_Date
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.Update_Date
     *
     * @param updateDate the value for m_user.Update_Date
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.DelFg
     *
     * @return the value of m_user.DelFg
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getDelfg() {
        return delfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.DelFg
     *
     * @param delfg the value for m_user.DelFg
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setDelfg(String delfg) {
        this.delfg = delfg == null ? null : delfg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.Beizhu
     *
     * @return the value of m_user.Beizhu
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.Beizhu
     *
     * @param beizhu the value for m_user.Beizhu
     *
     * @mbg.generated Mon Aug 26 14:48:06 CST 2019
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu == null ? null : beizhu.trim();
    }
}