package com.hdy.myhxc.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserDepExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public UserDepExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andDepNameIsNull() {
            addCriterion("Dep_Name is null");
            return (Criteria) this;
        }

        public Criteria andDepNameIsNotNull() {
            addCriterion("Dep_Name is not null");
            return (Criteria) this;
        }

        public Criteria andDepNameEqualTo(String value) {
            addCriterion("Dep_Name =", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameNotEqualTo(String value) {
            addCriterion("Dep_Name <>", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameGreaterThan(String value) {
            addCriterion("Dep_Name >", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameGreaterThanOrEqualTo(String value) {
            addCriterion("Dep_Name >=", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameLessThan(String value) {
            addCriterion("Dep_Name <", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameLessThanOrEqualTo(String value) {
            addCriterion("Dep_Name <=", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameLike(String value) {
            addCriterion("Dep_Name like", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameNotLike(String value) {
            addCriterion("Dep_Name not like", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameIn(List<String> values) {
            addCriterion("Dep_Name in", values, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameNotIn(List<String> values) {
            addCriterion("Dep_Name not in", values, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameBetween(String value1, String value2) {
            addCriterion("Dep_Name between", value1, value2, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameNotBetween(String value1, String value2) {
            addCriterion("Dep_Name not between", value1, value2, "depName");
            return (Criteria) this;
        }

        public Criteria andDepLevelIsNull() {
            addCriterion("Dep_Level is null");
            return (Criteria) this;
        }

        public Criteria andDepLevelIsNotNull() {
            addCriterion("Dep_Level is not null");
            return (Criteria) this;
        }

        public Criteria andDepLevelEqualTo(Integer value) {
            addCriterion("Dep_Level =", value, "depLevel");
            return (Criteria) this;
        }

        public Criteria andDepLevelNotEqualTo(Integer value) {
            addCriterion("Dep_Level <>", value, "depLevel");
            return (Criteria) this;
        }

        public Criteria andDepLevelGreaterThan(Integer value) {
            addCriterion("Dep_Level >", value, "depLevel");
            return (Criteria) this;
        }

        public Criteria andDepLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("Dep_Level >=", value, "depLevel");
            return (Criteria) this;
        }

        public Criteria andDepLevelLessThan(Integer value) {
            addCriterion("Dep_Level <", value, "depLevel");
            return (Criteria) this;
        }

        public Criteria andDepLevelLessThanOrEqualTo(Integer value) {
            addCriterion("Dep_Level <=", value, "depLevel");
            return (Criteria) this;
        }

        public Criteria andDepLevelIn(List<Integer> values) {
            addCriterion("Dep_Level in", values, "depLevel");
            return (Criteria) this;
        }

        public Criteria andDepLevelNotIn(List<Integer> values) {
            addCriterion("Dep_Level not in", values, "depLevel");
            return (Criteria) this;
        }

        public Criteria andDepLevelBetween(Integer value1, Integer value2) {
            addCriterion("Dep_Level between", value1, value2, "depLevel");
            return (Criteria) this;
        }

        public Criteria andDepLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("Dep_Level not between", value1, value2, "depLevel");
            return (Criteria) this;
        }

        public Criteria andDepTopidIsNull() {
            addCriterion("Dep_TopID is null");
            return (Criteria) this;
        }

        public Criteria andDepTopidIsNotNull() {
            addCriterion("Dep_TopID is not null");
            return (Criteria) this;
        }

        public Criteria andDepTopidEqualTo(String value) {
            addCriterion("Dep_TopID =", value, "depTopid");
            return (Criteria) this;
        }

        public Criteria andDepTopidNotEqualTo(String value) {
            addCriterion("Dep_TopID <>", value, "depTopid");
            return (Criteria) this;
        }

        public Criteria andDepTopidGreaterThan(String value) {
            addCriterion("Dep_TopID >", value, "depTopid");
            return (Criteria) this;
        }

        public Criteria andDepTopidGreaterThanOrEqualTo(String value) {
            addCriterion("Dep_TopID >=", value, "depTopid");
            return (Criteria) this;
        }

        public Criteria andDepTopidLessThan(String value) {
            addCriterion("Dep_TopID <", value, "depTopid");
            return (Criteria) this;
        }

        public Criteria andDepTopidLessThanOrEqualTo(String value) {
            addCriterion("Dep_TopID <=", value, "depTopid");
            return (Criteria) this;
        }

        public Criteria andDepTopidLike(String value) {
            addCriterion("Dep_TopID like", value, "depTopid");
            return (Criteria) this;
        }

        public Criteria andDepTopidNotLike(String value) {
            addCriterion("Dep_TopID not like", value, "depTopid");
            return (Criteria) this;
        }

        public Criteria andDepTopidIn(List<String> values) {
            addCriterion("Dep_TopID in", values, "depTopid");
            return (Criteria) this;
        }

        public Criteria andDepTopidNotIn(List<String> values) {
            addCriterion("Dep_TopID not in", values, "depTopid");
            return (Criteria) this;
        }

        public Criteria andDepTopidBetween(String value1, String value2) {
            addCriterion("Dep_TopID between", value1, value2, "depTopid");
            return (Criteria) this;
        }

        public Criteria andDepTopidNotBetween(String value1, String value2) {
            addCriterion("Dep_TopID not between", value1, value2, "depTopid");
            return (Criteria) this;
        }

        public Criteria andDepTopnameIsNull() {
            addCriterion("Dep_TopName is null");
            return (Criteria) this;
        }

        public Criteria andDepTopnameIsNotNull() {
            addCriterion("Dep_TopName is not null");
            return (Criteria) this;
        }

        public Criteria andDepTopnameEqualTo(String value) {
            addCriterion("Dep_TopName =", value, "depTopname");
            return (Criteria) this;
        }

        public Criteria andDepTopnameNotEqualTo(String value) {
            addCriterion("Dep_TopName <>", value, "depTopname");
            return (Criteria) this;
        }

        public Criteria andDepTopnameGreaterThan(String value) {
            addCriterion("Dep_TopName >", value, "depTopname");
            return (Criteria) this;
        }

        public Criteria andDepTopnameGreaterThanOrEqualTo(String value) {
            addCriterion("Dep_TopName >=", value, "depTopname");
            return (Criteria) this;
        }

        public Criteria andDepTopnameLessThan(String value) {
            addCriterion("Dep_TopName <", value, "depTopname");
            return (Criteria) this;
        }

        public Criteria andDepTopnameLessThanOrEqualTo(String value) {
            addCriterion("Dep_TopName <=", value, "depTopname");
            return (Criteria) this;
        }

        public Criteria andDepTopnameLike(String value) {
            addCriterion("Dep_TopName like", value, "depTopname");
            return (Criteria) this;
        }

        public Criteria andDepTopnameNotLike(String value) {
            addCriterion("Dep_TopName not like", value, "depTopname");
            return (Criteria) this;
        }

        public Criteria andDepTopnameIn(List<String> values) {
            addCriterion("Dep_TopName in", values, "depTopname");
            return (Criteria) this;
        }

        public Criteria andDepTopnameNotIn(List<String> values) {
            addCriterion("Dep_TopName not in", values, "depTopname");
            return (Criteria) this;
        }

        public Criteria andDepTopnameBetween(String value1, String value2) {
            addCriterion("Dep_TopName between", value1, value2, "depTopname");
            return (Criteria) this;
        }

        public Criteria andDepTopnameNotBetween(String value1, String value2) {
            addCriterion("Dep_TopName not between", value1, value2, "depTopname");
            return (Criteria) this;
        }

        public Criteria andShowIdxIsNull() {
            addCriterion("Show_Idx is null");
            return (Criteria) this;
        }

        public Criteria andShowIdxIsNotNull() {
            addCriterion("Show_Idx is not null");
            return (Criteria) this;
        }

        public Criteria andShowIdxEqualTo(Integer value) {
            addCriterion("Show_Idx =", value, "showIdx");
            return (Criteria) this;
        }

        public Criteria andShowIdxNotEqualTo(Integer value) {
            addCriterion("Show_Idx <>", value, "showIdx");
            return (Criteria) this;
        }

        public Criteria andShowIdxGreaterThan(Integer value) {
            addCriterion("Show_Idx >", value, "showIdx");
            return (Criteria) this;
        }

        public Criteria andShowIdxGreaterThanOrEqualTo(Integer value) {
            addCriterion("Show_Idx >=", value, "showIdx");
            return (Criteria) this;
        }

        public Criteria andShowIdxLessThan(Integer value) {
            addCriterion("Show_Idx <", value, "showIdx");
            return (Criteria) this;
        }

        public Criteria andShowIdxLessThanOrEqualTo(Integer value) {
            addCriterion("Show_Idx <=", value, "showIdx");
            return (Criteria) this;
        }

        public Criteria andShowIdxIn(List<Integer> values) {
            addCriterion("Show_Idx in", values, "showIdx");
            return (Criteria) this;
        }

        public Criteria andShowIdxNotIn(List<Integer> values) {
            addCriterion("Show_Idx not in", values, "showIdx");
            return (Criteria) this;
        }

        public Criteria andShowIdxBetween(Integer value1, Integer value2) {
            addCriterion("Show_Idx between", value1, value2, "showIdx");
            return (Criteria) this;
        }

        public Criteria andShowIdxNotBetween(Integer value1, Integer value2) {
            addCriterion("Show_Idx not between", value1, value2, "showIdx");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("Create_User is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("Create_User is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("Create_User =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("Create_User <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("Create_User >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("Create_User >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("Create_User <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("Create_User <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("Create_User like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("Create_User not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("Create_User in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("Create_User not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("Create_User between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("Create_User not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("Create_Date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("Create_Date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("Create_Date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("Create_Date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("Create_Date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("Create_Date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("Create_Date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("Create_Date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("Create_Date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("Create_Date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("Create_Date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("Create_Date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("Update_User is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("Update_User is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("Update_User =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("Update_User <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("Update_User >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("Update_User >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("Update_User <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("Update_User <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("Update_User like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("Update_User not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("Update_User in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("Update_User not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("Update_User between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("Update_User not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("Update_Date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("Update_Date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("Update_Date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("Update_Date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("Update_Date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("Update_Date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("Update_Date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("Update_Date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("Update_Date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("Update_Date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("Update_Date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("Update_Date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andDelfgIsNull() {
            addCriterion("DelFg is null");
            return (Criteria) this;
        }

        public Criteria andDelfgIsNotNull() {
            addCriterion("DelFg is not null");
            return (Criteria) this;
        }

        public Criteria andDelfgEqualTo(String value) {
            addCriterion("DelFg =", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgNotEqualTo(String value) {
            addCriterion("DelFg <>", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgGreaterThan(String value) {
            addCriterion("DelFg >", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgGreaterThanOrEqualTo(String value) {
            addCriterion("DelFg >=", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgLessThan(String value) {
            addCriterion("DelFg <", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgLessThanOrEqualTo(String value) {
            addCriterion("DelFg <=", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgLike(String value) {
            addCriterion("DelFg like", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgNotLike(String value) {
            addCriterion("DelFg not like", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgIn(List<String> values) {
            addCriterion("DelFg in", values, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgNotIn(List<String> values) {
            addCriterion("DelFg not in", values, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgBetween(String value1, String value2) {
            addCriterion("DelFg between", value1, value2, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgNotBetween(String value1, String value2) {
            addCriterion("DelFg not between", value1, value2, "delfg");
            return (Criteria) this;
        }

        public Criteria andBeizhuIsNull() {
            addCriterion("Beizhu is null");
            return (Criteria) this;
        }

        public Criteria andBeizhuIsNotNull() {
            addCriterion("Beizhu is not null");
            return (Criteria) this;
        }

        public Criteria andBeizhuEqualTo(String value) {
            addCriterion("Beizhu =", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuNotEqualTo(String value) {
            addCriterion("Beizhu <>", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuGreaterThan(String value) {
            addCriterion("Beizhu >", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuGreaterThanOrEqualTo(String value) {
            addCriterion("Beizhu >=", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuLessThan(String value) {
            addCriterion("Beizhu <", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuLessThanOrEqualTo(String value) {
            addCriterion("Beizhu <=", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuLike(String value) {
            addCriterion("Beizhu like", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuNotLike(String value) {
            addCriterion("Beizhu not like", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuIn(List<String> values) {
            addCriterion("Beizhu in", values, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuNotIn(List<String> values) {
            addCriterion("Beizhu not in", values, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuBetween(String value1, String value2) {
            addCriterion("Beizhu between", value1, value2, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuNotBetween(String value1, String value2) {
            addCriterion("Beizhu not between", value1, value2, "beizhu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_userdep
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 26 14:48:07 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_userdep
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}