package com.hdy.myhxc.model;

import java.util.Date;

public class Userdep {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userdep.UUID
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userdep.Dep_Name
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    private String depName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userdep.Dep_Level
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    private Integer depLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userdep.Dep_TopID
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    private String depTopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userdep.Dep_TopName
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    private String depTopname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userdep.Show_Idx
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    private Integer showIdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userdep.Create_User
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userdep.Create_Date
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userdep.Update_User
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userdep.Update_Date
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userdep.DelFg
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    private String delfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userdep.Beizhu
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    private String beizhu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userdep.UUID
     *
     * @return the value of m_userdep.UUID
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userdep.UUID
     *
     * @param uuid the value for m_userdep.UUID
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userdep.Dep_Name
     *
     * @return the value of m_userdep.Dep_Name
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userdep.Dep_Name
     *
     * @param depName the value for m_userdep.Dep_Name
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userdep.Dep_Level
     *
     * @return the value of m_userdep.Dep_Level
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public Integer getDepLevel() {
        return depLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userdep.Dep_Level
     *
     * @param depLevel the value for m_userdep.Dep_Level
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setDepLevel(Integer depLevel) {
        this.depLevel = depLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userdep.Dep_TopID
     *
     * @return the value of m_userdep.Dep_TopID
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public String getDepTopid() {
        return depTopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userdep.Dep_TopID
     *
     * @param depTopid the value for m_userdep.Dep_TopID
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setDepTopid(String depTopid) {
        this.depTopid = depTopid == null ? null : depTopid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userdep.Dep_TopName
     *
     * @return the value of m_userdep.Dep_TopName
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public String getDepTopname() {
        return depTopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userdep.Dep_TopName
     *
     * @param depTopname the value for m_userdep.Dep_TopName
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setDepTopname(String depTopname) {
        this.depTopname = depTopname == null ? null : depTopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userdep.Show_Idx
     *
     * @return the value of m_userdep.Show_Idx
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public Integer getShowIdx() {
        return showIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userdep.Show_Idx
     *
     * @param showIdx the value for m_userdep.Show_Idx
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setShowIdx(Integer showIdx) {
        this.showIdx = showIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userdep.Create_User
     *
     * @return the value of m_userdep.Create_User
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userdep.Create_User
     *
     * @param createUser the value for m_userdep.Create_User
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userdep.Create_Date
     *
     * @return the value of m_userdep.Create_Date
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userdep.Create_Date
     *
     * @param createDate the value for m_userdep.Create_Date
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userdep.Update_User
     *
     * @return the value of m_userdep.Update_User
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userdep.Update_User
     *
     * @param updateUser the value for m_userdep.Update_User
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userdep.Update_Date
     *
     * @return the value of m_userdep.Update_Date
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userdep.Update_Date
     *
     * @param updateDate the value for m_userdep.Update_Date
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userdep.DelFg
     *
     * @return the value of m_userdep.DelFg
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public String getDelfg() {
        return delfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userdep.DelFg
     *
     * @param delfg the value for m_userdep.DelFg
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setDelfg(String delfg) {
        this.delfg = delfg == null ? null : delfg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userdep.Beizhu
     *
     * @return the value of m_userdep.Beizhu
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userdep.Beizhu
     *
     * @param beizhu the value for m_userdep.Beizhu
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu == null ? null : beizhu.trim();
    }
}