package com.hdy.myhxc.model;

import java.util.Date;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userrole.UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userrole.User_UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String userUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userrole.Role_UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String roleUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userrole.Create_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userrole.Create_Data
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private Date createData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userrole.Update_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userrole.Update_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userrole.DelFg
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String delfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_userrole.Beizhu
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    private String beizhu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userrole.UUID
     *
     * @return the value of m_userrole.UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userrole.UUID
     *
     * @param uuid the value for m_userrole.UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userrole.User_UUID
     *
     * @return the value of m_userrole.User_UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userrole.User_UUID
     *
     * @param userUuid the value for m_userrole.User_UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userrole.Role_UUID
     *
     * @return the value of m_userrole.Role_UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getRoleUuid() {
        return roleUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userrole.Role_UUID
     *
     * @param roleUuid the value for m_userrole.Role_UUID
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setRoleUuid(String roleUuid) {
        this.roleUuid = roleUuid == null ? null : roleUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userrole.Create_User
     *
     * @return the value of m_userrole.Create_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userrole.Create_User
     *
     * @param createUser the value for m_userrole.Create_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userrole.Create_Data
     *
     * @return the value of m_userrole.Create_Data
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public Date getCreateData() {
        return createData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userrole.Create_Data
     *
     * @param createData the value for m_userrole.Create_Data
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setCreateData(Date createData) {
        this.createData = createData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userrole.Update_User
     *
     * @return the value of m_userrole.Update_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userrole.Update_User
     *
     * @param updateUser the value for m_userrole.Update_User
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userrole.Update_Date
     *
     * @return the value of m_userrole.Update_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userrole.Update_Date
     *
     * @param updateDate the value for m_userrole.Update_Date
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userrole.DelFg
     *
     * @return the value of m_userrole.DelFg
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getDelfg() {
        return delfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userrole.DelFg
     *
     * @param delfg the value for m_userrole.DelFg
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setDelfg(String delfg) {
        this.delfg = delfg == null ? null : delfg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_userrole.Beizhu
     *
     * @return the value of m_userrole.Beizhu
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_userrole.Beizhu
     *
     * @param beizhu the value for m_userrole.Beizhu
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu == null ? null : beizhu.trim();
    }
}