package com.hdy.myhxc.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUserCodeIsNull() {
            addCriterion("User_Code is null");
            return (Criteria) this;
        }

        public Criteria andUserCodeIsNotNull() {
            addCriterion("User_Code is not null");
            return (Criteria) this;
        }

        public Criteria andUserCodeEqualTo(String value) {
            addCriterion("User_Code =", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotEqualTo(String value) {
            addCriterion("User_Code <>", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeGreaterThan(String value) {
            addCriterion("User_Code >", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("User_Code >=", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLessThan(String value) {
            addCriterion("User_Code <", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLessThanOrEqualTo(String value) {
            addCriterion("User_Code <=", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLike(String value) {
            addCriterion("User_Code like", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotLike(String value) {
            addCriterion("User_Code not like", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeIn(List<String> values) {
            addCriterion("User_Code in", values, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotIn(List<String> values) {
            addCriterion("User_Code not in", values, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeBetween(String value1, String value2) {
            addCriterion("User_Code between", value1, value2, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotBetween(String value1, String value2) {
            addCriterion("User_Code not between", value1, value2, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserPsdIsNull() {
            addCriterion("User_Psd is null");
            return (Criteria) this;
        }

        public Criteria andUserPsdIsNotNull() {
            addCriterion("User_Psd is not null");
            return (Criteria) this;
        }

        public Criteria andUserPsdEqualTo(String value) {
            addCriterion("User_Psd =", value, "userPsd");
            return (Criteria) this;
        }

        public Criteria andUserPsdNotEqualTo(String value) {
            addCriterion("User_Psd <>", value, "userPsd");
            return (Criteria) this;
        }

        public Criteria andUserPsdGreaterThan(String value) {
            addCriterion("User_Psd >", value, "userPsd");
            return (Criteria) this;
        }

        public Criteria andUserPsdGreaterThanOrEqualTo(String value) {
            addCriterion("User_Psd >=", value, "userPsd");
            return (Criteria) this;
        }

        public Criteria andUserPsdLessThan(String value) {
            addCriterion("User_Psd <", value, "userPsd");
            return (Criteria) this;
        }

        public Criteria andUserPsdLessThanOrEqualTo(String value) {
            addCriterion("User_Psd <=", value, "userPsd");
            return (Criteria) this;
        }

        public Criteria andUserPsdLike(String value) {
            addCriterion("User_Psd like", value, "userPsd");
            return (Criteria) this;
        }

        public Criteria andUserPsdNotLike(String value) {
            addCriterion("User_Psd not like", value, "userPsd");
            return (Criteria) this;
        }

        public Criteria andUserPsdIn(List<String> values) {
            addCriterion("User_Psd in", values, "userPsd");
            return (Criteria) this;
        }

        public Criteria andUserPsdNotIn(List<String> values) {
            addCriterion("User_Psd not in", values, "userPsd");
            return (Criteria) this;
        }

        public Criteria andUserPsdBetween(String value1, String value2) {
            addCriterion("User_Psd between", value1, value2, "userPsd");
            return (Criteria) this;
        }

        public Criteria andUserPsdNotBetween(String value1, String value2) {
            addCriterion("User_Psd not between", value1, value2, "userPsd");
            return (Criteria) this;
        }

        public Criteria andUserDepIsNull() {
            addCriterion("User_Dep is null");
            return (Criteria) this;
        }

        public Criteria andUserDepIsNotNull() {
            addCriterion("User_Dep is not null");
            return (Criteria) this;
        }

        public Criteria andUserDepEqualTo(String value) {
            addCriterion("User_Dep =", value, "userDep");
            return (Criteria) this;
        }

        public Criteria andUserDepNotEqualTo(String value) {
            addCriterion("User_Dep <>", value, "userDep");
            return (Criteria) this;
        }

        public Criteria andUserDepGreaterThan(String value) {
            addCriterion("User_Dep >", value, "userDep");
            return (Criteria) this;
        }

        public Criteria andUserDepGreaterThanOrEqualTo(String value) {
            addCriterion("User_Dep >=", value, "userDep");
            return (Criteria) this;
        }

        public Criteria andUserDepLessThan(String value) {
            addCriterion("User_Dep <", value, "userDep");
            return (Criteria) this;
        }

        public Criteria andUserDepLessThanOrEqualTo(String value) {
            addCriterion("User_Dep <=", value, "userDep");
            return (Criteria) this;
        }

        public Criteria andUserDepLike(String value) {
            addCriterion("User_Dep like", value, "userDep");
            return (Criteria) this;
        }

        public Criteria andUserDepNotLike(String value) {
            addCriterion("User_Dep not like", value, "userDep");
            return (Criteria) this;
        }

        public Criteria andUserDepIn(List<String> values) {
            addCriterion("User_Dep in", values, "userDep");
            return (Criteria) this;
        }

        public Criteria andUserDepNotIn(List<String> values) {
            addCriterion("User_Dep not in", values, "userDep");
            return (Criteria) this;
        }

        public Criteria andUserDepBetween(String value1, String value2) {
            addCriterion("User_Dep between", value1, value2, "userDep");
            return (Criteria) this;
        }

        public Criteria andUserDepNotBetween(String value1, String value2) {
            addCriterion("User_Dep not between", value1, value2, "userDep");
            return (Criteria) this;
        }

        public Criteria andUserDepnmIsNull() {
            addCriterion("User_DepNM is null");
            return (Criteria) this;
        }

        public Criteria andUserDepnmIsNotNull() {
            addCriterion("User_DepNM is not null");
            return (Criteria) this;
        }

        public Criteria andUserDepnmEqualTo(String value) {
            addCriterion("User_DepNM =", value, "userDepnm");
            return (Criteria) this;
        }

        public Criteria andUserDepnmNotEqualTo(String value) {
            addCriterion("User_DepNM <>", value, "userDepnm");
            return (Criteria) this;
        }

        public Criteria andUserDepnmGreaterThan(String value) {
            addCriterion("User_DepNM >", value, "userDepnm");
            return (Criteria) this;
        }

        public Criteria andUserDepnmGreaterThanOrEqualTo(String value) {
            addCriterion("User_DepNM >=", value, "userDepnm");
            return (Criteria) this;
        }

        public Criteria andUserDepnmLessThan(String value) {
            addCriterion("User_DepNM <", value, "userDepnm");
            return (Criteria) this;
        }

        public Criteria andUserDepnmLessThanOrEqualTo(String value) {
            addCriterion("User_DepNM <=", value, "userDepnm");
            return (Criteria) this;
        }

        public Criteria andUserDepnmLike(String value) {
            addCriterion("User_DepNM like", value, "userDepnm");
            return (Criteria) this;
        }

        public Criteria andUserDepnmNotLike(String value) {
            addCriterion("User_DepNM not like", value, "userDepnm");
            return (Criteria) this;
        }

        public Criteria andUserDepnmIn(List<String> values) {
            addCriterion("User_DepNM in", values, "userDepnm");
            return (Criteria) this;
        }

        public Criteria andUserDepnmNotIn(List<String> values) {
            addCriterion("User_DepNM not in", values, "userDepnm");
            return (Criteria) this;
        }

        public Criteria andUserDepnmBetween(String value1, String value2) {
            addCriterion("User_DepNM between", value1, value2, "userDepnm");
            return (Criteria) this;
        }

        public Criteria andUserDepnmNotBetween(String value1, String value2) {
            addCriterion("User_DepNM not between", value1, value2, "userDepnm");
            return (Criteria) this;
        }

        public Criteria andUserNmIsNull() {
            addCriterion("User_NM is null");
            return (Criteria) this;
        }

        public Criteria andUserNmIsNotNull() {
            addCriterion("User_NM is not null");
            return (Criteria) this;
        }

        public Criteria andUserNmEqualTo(String value) {
            addCriterion("User_NM =", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmNotEqualTo(String value) {
            addCriterion("User_NM <>", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmGreaterThan(String value) {
            addCriterion("User_NM >", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmGreaterThanOrEqualTo(String value) {
            addCriterion("User_NM >=", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmLessThan(String value) {
            addCriterion("User_NM <", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmLessThanOrEqualTo(String value) {
            addCriterion("User_NM <=", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmLike(String value) {
            addCriterion("User_NM like", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmNotLike(String value) {
            addCriterion("User_NM not like", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmIn(List<String> values) {
            addCriterion("User_NM in", values, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmNotIn(List<String> values) {
            addCriterion("User_NM not in", values, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmBetween(String value1, String value2) {
            addCriterion("User_NM between", value1, value2, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmNotBetween(String value1, String value2) {
            addCriterion("User_NM not between", value1, value2, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserGenderIsNull() {
            addCriterion("User_Gender is null");
            return (Criteria) this;
        }

        public Criteria andUserGenderIsNotNull() {
            addCriterion("User_Gender is not null");
            return (Criteria) this;
        }

        public Criteria andUserGenderEqualTo(String value) {
            addCriterion("User_Gender =", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderNotEqualTo(String value) {
            addCriterion("User_Gender <>", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderGreaterThan(String value) {
            addCriterion("User_Gender >", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderGreaterThanOrEqualTo(String value) {
            addCriterion("User_Gender >=", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderLessThan(String value) {
            addCriterion("User_Gender <", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderLessThanOrEqualTo(String value) {
            addCriterion("User_Gender <=", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderLike(String value) {
            addCriterion("User_Gender like", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderNotLike(String value) {
            addCriterion("User_Gender not like", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderIn(List<String> values) {
            addCriterion("User_Gender in", values, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderNotIn(List<String> values) {
            addCriterion("User_Gender not in", values, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderBetween(String value1, String value2) {
            addCriterion("User_Gender between", value1, value2, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderNotBetween(String value1, String value2) {
            addCriterion("User_Gender not between", value1, value2, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserTelIsNull() {
            addCriterion("User_Tel is null");
            return (Criteria) this;
        }

        public Criteria andUserTelIsNotNull() {
            addCriterion("User_Tel is not null");
            return (Criteria) this;
        }

        public Criteria andUserTelEqualTo(String value) {
            addCriterion("User_Tel =", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelNotEqualTo(String value) {
            addCriterion("User_Tel <>", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelGreaterThan(String value) {
            addCriterion("User_Tel >", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelGreaterThanOrEqualTo(String value) {
            addCriterion("User_Tel >=", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelLessThan(String value) {
            addCriterion("User_Tel <", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelLessThanOrEqualTo(String value) {
            addCriterion("User_Tel <=", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelLike(String value) {
            addCriterion("User_Tel like", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelNotLike(String value) {
            addCriterion("User_Tel not like", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelIn(List<String> values) {
            addCriterion("User_Tel in", values, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelNotIn(List<String> values) {
            addCriterion("User_Tel not in", values, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelBetween(String value1, String value2) {
            addCriterion("User_Tel between", value1, value2, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelNotBetween(String value1, String value2) {
            addCriterion("User_Tel not between", value1, value2, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserRoleIsNull() {
            addCriterion("User_Role is null");
            return (Criteria) this;
        }

        public Criteria andUserRoleIsNotNull() {
            addCriterion("User_Role is not null");
            return (Criteria) this;
        }

        public Criteria andUserRoleEqualTo(String value) {
            addCriterion("User_Role =", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleNotEqualTo(String value) {
            addCriterion("User_Role <>", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleGreaterThan(String value) {
            addCriterion("User_Role >", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleGreaterThanOrEqualTo(String value) {
            addCriterion("User_Role >=", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleLessThan(String value) {
            addCriterion("User_Role <", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleLessThanOrEqualTo(String value) {
            addCriterion("User_Role <=", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleLike(String value) {
            addCriterion("User_Role like", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleNotLike(String value) {
            addCriterion("User_Role not like", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleIn(List<String> values) {
            addCriterion("User_Role in", values, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleNotIn(List<String> values) {
            addCriterion("User_Role not in", values, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleBetween(String value1, String value2) {
            addCriterion("User_Role between", value1, value2, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleNotBetween(String value1, String value2) {
            addCriterion("User_Role not between", value1, value2, "userRole");
            return (Criteria) this;
        }

        public Criteria andUpdatePwdtIsNull() {
            addCriterion("Update_PWDT is null");
            return (Criteria) this;
        }

        public Criteria andUpdatePwdtIsNotNull() {
            addCriterion("Update_PWDT is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatePwdtEqualTo(Date value) {
            addCriterion("Update_PWDT =", value, "updatePwdt");
            return (Criteria) this;
        }

        public Criteria andUpdatePwdtNotEqualTo(Date value) {
            addCriterion("Update_PWDT <>", value, "updatePwdt");
            return (Criteria) this;
        }

        public Criteria andUpdatePwdtGreaterThan(Date value) {
            addCriterion("Update_PWDT >", value, "updatePwdt");
            return (Criteria) this;
        }

        public Criteria andUpdatePwdtGreaterThanOrEqualTo(Date value) {
            addCriterion("Update_PWDT >=", value, "updatePwdt");
            return (Criteria) this;
        }

        public Criteria andUpdatePwdtLessThan(Date value) {
            addCriterion("Update_PWDT <", value, "updatePwdt");
            return (Criteria) this;
        }

        public Criteria andUpdatePwdtLessThanOrEqualTo(Date value) {
            addCriterion("Update_PWDT <=", value, "updatePwdt");
            return (Criteria) this;
        }

        public Criteria andUpdatePwdtIn(List<Date> values) {
            addCriterion("Update_PWDT in", values, "updatePwdt");
            return (Criteria) this;
        }

        public Criteria andUpdatePwdtNotIn(List<Date> values) {
            addCriterion("Update_PWDT not in", values, "updatePwdt");
            return (Criteria) this;
        }

        public Criteria andUpdatePwdtBetween(Date value1, Date value2) {
            addCriterion("Update_PWDT between", value1, value2, "updatePwdt");
            return (Criteria) this;
        }

        public Criteria andUpdatePwdtNotBetween(Date value1, Date value2) {
            addCriterion("Update_PWDT not between", value1, value2, "updatePwdt");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitIsNull() {
            addCriterion("IsConstructionUnit is null");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitIsNotNull() {
            addCriterion("IsConstructionUnit is not null");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitEqualTo(String value) {
            addCriterion("IsConstructionUnit =", value, "isconstructionunit");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitNotEqualTo(String value) {
            addCriterion("IsConstructionUnit <>", value, "isconstructionunit");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitGreaterThan(String value) {
            addCriterion("IsConstructionUnit >", value, "isconstructionunit");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitGreaterThanOrEqualTo(String value) {
            addCriterion("IsConstructionUnit >=", value, "isconstructionunit");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitLessThan(String value) {
            addCriterion("IsConstructionUnit <", value, "isconstructionunit");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitLessThanOrEqualTo(String value) {
            addCriterion("IsConstructionUnit <=", value, "isconstructionunit");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitLike(String value) {
            addCriterion("IsConstructionUnit like", value, "isconstructionunit");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitNotLike(String value) {
            addCriterion("IsConstructionUnit not like", value, "isconstructionunit");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitIn(List<String> values) {
            addCriterion("IsConstructionUnit in", values, "isconstructionunit");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitNotIn(List<String> values) {
            addCriterion("IsConstructionUnit not in", values, "isconstructionunit");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitBetween(String value1, String value2) {
            addCriterion("IsConstructionUnit between", value1, value2, "isconstructionunit");
            return (Criteria) this;
        }

        public Criteria andIsconstructionunitNotBetween(String value1, String value2) {
            addCriterion("IsConstructionUnit not between", value1, value2, "isconstructionunit");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolIsNull() {
            addCriterion("IsRoadPatrol is null");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolIsNotNull() {
            addCriterion("IsRoadPatrol is not null");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolEqualTo(String value) {
            addCriterion("IsRoadPatrol =", value, "isroadpatrol");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolNotEqualTo(String value) {
            addCriterion("IsRoadPatrol <>", value, "isroadpatrol");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolGreaterThan(String value) {
            addCriterion("IsRoadPatrol >", value, "isroadpatrol");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolGreaterThanOrEqualTo(String value) {
            addCriterion("IsRoadPatrol >=", value, "isroadpatrol");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolLessThan(String value) {
            addCriterion("IsRoadPatrol <", value, "isroadpatrol");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolLessThanOrEqualTo(String value) {
            addCriterion("IsRoadPatrol <=", value, "isroadpatrol");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolLike(String value) {
            addCriterion("IsRoadPatrol like", value, "isroadpatrol");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolNotLike(String value) {
            addCriterion("IsRoadPatrol not like", value, "isroadpatrol");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolIn(List<String> values) {
            addCriterion("IsRoadPatrol in", values, "isroadpatrol");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolNotIn(List<String> values) {
            addCriterion("IsRoadPatrol not in", values, "isroadpatrol");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolBetween(String value1, String value2) {
            addCriterion("IsRoadPatrol between", value1, value2, "isroadpatrol");
            return (Criteria) this;
        }

        public Criteria andIsroadpatrolNotBetween(String value1, String value2) {
            addCriterion("IsRoadPatrol not between", value1, value2, "isroadpatrol");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuIsNull() {
            addCriterion("IsDesignatedCU is null");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuIsNotNull() {
            addCriterion("IsDesignatedCU is not null");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuEqualTo(String value) {
            addCriterion("IsDesignatedCU =", value, "isdesignatedcu");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuNotEqualTo(String value) {
            addCriterion("IsDesignatedCU <>", value, "isdesignatedcu");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuGreaterThan(String value) {
            addCriterion("IsDesignatedCU >", value, "isdesignatedcu");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuGreaterThanOrEqualTo(String value) {
            addCriterion("IsDesignatedCU >=", value, "isdesignatedcu");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuLessThan(String value) {
            addCriterion("IsDesignatedCU <", value, "isdesignatedcu");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuLessThanOrEqualTo(String value) {
            addCriterion("IsDesignatedCU <=", value, "isdesignatedcu");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuLike(String value) {
            addCriterion("IsDesignatedCU like", value, "isdesignatedcu");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuNotLike(String value) {
            addCriterion("IsDesignatedCU not like", value, "isdesignatedcu");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuIn(List<String> values) {
            addCriterion("IsDesignatedCU in", values, "isdesignatedcu");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuNotIn(List<String> values) {
            addCriterion("IsDesignatedCU not in", values, "isdesignatedcu");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuBetween(String value1, String value2) {
            addCriterion("IsDesignatedCU between", value1, value2, "isdesignatedcu");
            return (Criteria) this;
        }

        public Criteria andIsdesignatedcuNotBetween(String value1, String value2) {
            addCriterion("IsDesignatedCU not between", value1, value2, "isdesignatedcu");
            return (Criteria) this;
        }

        public Criteria andIsendtaskIsNull() {
            addCriterion("IsEndTask is null");
            return (Criteria) this;
        }

        public Criteria andIsendtaskIsNotNull() {
            addCriterion("IsEndTask is not null");
            return (Criteria) this;
        }

        public Criteria andIsendtaskEqualTo(String value) {
            addCriterion("IsEndTask =", value, "isendtask");
            return (Criteria) this;
        }

        public Criteria andIsendtaskNotEqualTo(String value) {
            addCriterion("IsEndTask <>", value, "isendtask");
            return (Criteria) this;
        }

        public Criteria andIsendtaskGreaterThan(String value) {
            addCriterion("IsEndTask >", value, "isendtask");
            return (Criteria) this;
        }

        public Criteria andIsendtaskGreaterThanOrEqualTo(String value) {
            addCriterion("IsEndTask >=", value, "isendtask");
            return (Criteria) this;
        }

        public Criteria andIsendtaskLessThan(String value) {
            addCriterion("IsEndTask <", value, "isendtask");
            return (Criteria) this;
        }

        public Criteria andIsendtaskLessThanOrEqualTo(String value) {
            addCriterion("IsEndTask <=", value, "isendtask");
            return (Criteria) this;
        }

        public Criteria andIsendtaskLike(String value) {
            addCriterion("IsEndTask like", value, "isendtask");
            return (Criteria) this;
        }

        public Criteria andIsendtaskNotLike(String value) {
            addCriterion("IsEndTask not like", value, "isendtask");
            return (Criteria) this;
        }

        public Criteria andIsendtaskIn(List<String> values) {
            addCriterion("IsEndTask in", values, "isendtask");
            return (Criteria) this;
        }

        public Criteria andIsendtaskNotIn(List<String> values) {
            addCriterion("IsEndTask not in", values, "isendtask");
            return (Criteria) this;
        }

        public Criteria andIsendtaskBetween(String value1, String value2) {
            addCriterion("IsEndTask between", value1, value2, "isendtask");
            return (Criteria) this;
        }

        public Criteria andIsendtaskNotBetween(String value1, String value2) {
            addCriterion("IsEndTask not between", value1, value2, "isendtask");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceIsNull() {
            addCriterion("Handheld_Device is null");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceIsNotNull() {
            addCriterion("Handheld_Device is not null");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceEqualTo(String value) {
            addCriterion("Handheld_Device =", value, "handheldDevice");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceNotEqualTo(String value) {
            addCriterion("Handheld_Device <>", value, "handheldDevice");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceGreaterThan(String value) {
            addCriterion("Handheld_Device >", value, "handheldDevice");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceGreaterThanOrEqualTo(String value) {
            addCriterion("Handheld_Device >=", value, "handheldDevice");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceLessThan(String value) {
            addCriterion("Handheld_Device <", value, "handheldDevice");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceLessThanOrEqualTo(String value) {
            addCriterion("Handheld_Device <=", value, "handheldDevice");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceLike(String value) {
            addCriterion("Handheld_Device like", value, "handheldDevice");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceNotLike(String value) {
            addCriterion("Handheld_Device not like", value, "handheldDevice");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceIn(List<String> values) {
            addCriterion("Handheld_Device in", values, "handheldDevice");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceNotIn(List<String> values) {
            addCriterion("Handheld_Device not in", values, "handheldDevice");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceBetween(String value1, String value2) {
            addCriterion("Handheld_Device between", value1, value2, "handheldDevice");
            return (Criteria) this;
        }

        public Criteria andHandheldDeviceNotBetween(String value1, String value2) {
            addCriterion("Handheld_Device not between", value1, value2, "handheldDevice");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdIsNull() {
            addCriterion("JGRegister_ID is null");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdIsNotNull() {
            addCriterion("JGRegister_ID is not null");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdEqualTo(String value) {
            addCriterion("JGRegister_ID =", value, "jgregisterId");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdNotEqualTo(String value) {
            addCriterion("JGRegister_ID <>", value, "jgregisterId");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdGreaterThan(String value) {
            addCriterion("JGRegister_ID >", value, "jgregisterId");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdGreaterThanOrEqualTo(String value) {
            addCriterion("JGRegister_ID >=", value, "jgregisterId");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdLessThan(String value) {
            addCriterion("JGRegister_ID <", value, "jgregisterId");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdLessThanOrEqualTo(String value) {
            addCriterion("JGRegister_ID <=", value, "jgregisterId");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdLike(String value) {
            addCriterion("JGRegister_ID like", value, "jgregisterId");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdNotLike(String value) {
            addCriterion("JGRegister_ID not like", value, "jgregisterId");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdIn(List<String> values) {
            addCriterion("JGRegister_ID in", values, "jgregisterId");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdNotIn(List<String> values) {
            addCriterion("JGRegister_ID not in", values, "jgregisterId");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdBetween(String value1, String value2) {
            addCriterion("JGRegister_ID between", value1, value2, "jgregisterId");
            return (Criteria) this;
        }

        public Criteria andJgregisterIdNotBetween(String value1, String value2) {
            addCriterion("JGRegister_ID not between", value1, value2, "jgregisterId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("Create_User is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("Create_User is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("Create_User =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("Create_User <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("Create_User >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("Create_User >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("Create_User <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("Create_User <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("Create_User like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("Create_User not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("Create_User in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("Create_User not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("Create_User between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("Create_User not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("Create_Date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("Create_Date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("Create_Date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("Create_Date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("Create_Date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("Create_Date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("Create_Date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("Create_Date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("Create_Date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("Create_Date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("Create_Date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("Create_Date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("Update_User is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("Update_User is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("Update_User =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("Update_User <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("Update_User >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("Update_User >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("Update_User <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("Update_User <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("Update_User like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("Update_User not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("Update_User in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("Update_User not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("Update_User between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("Update_User not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("Update_Date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("Update_Date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("Update_Date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("Update_Date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("Update_Date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("Update_Date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("Update_Date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("Update_Date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("Update_Date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("Update_Date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("Update_Date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("Update_Date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andDelfgIsNull() {
            addCriterion("DelFg is null");
            return (Criteria) this;
        }

        public Criteria andDelfgIsNotNull() {
            addCriterion("DelFg is not null");
            return (Criteria) this;
        }

        public Criteria andDelfgEqualTo(String value) {
            addCriterion("DelFg =", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgNotEqualTo(String value) {
            addCriterion("DelFg <>", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgGreaterThan(String value) {
            addCriterion("DelFg >", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgGreaterThanOrEqualTo(String value) {
            addCriterion("DelFg >=", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgLessThan(String value) {
            addCriterion("DelFg <", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgLessThanOrEqualTo(String value) {
            addCriterion("DelFg <=", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgLike(String value) {
            addCriterion("DelFg like", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgNotLike(String value) {
            addCriterion("DelFg not like", value, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgIn(List<String> values) {
            addCriterion("DelFg in", values, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgNotIn(List<String> values) {
            addCriterion("DelFg not in", values, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgBetween(String value1, String value2) {
            addCriterion("DelFg between", value1, value2, "delfg");
            return (Criteria) this;
        }

        public Criteria andDelfgNotBetween(String value1, String value2) {
            addCriterion("DelFg not between", value1, value2, "delfg");
            return (Criteria) this;
        }

        public Criteria andBeizhuIsNull() {
            addCriterion("Beizhu is null");
            return (Criteria) this;
        }

        public Criteria andBeizhuIsNotNull() {
            addCriterion("Beizhu is not null");
            return (Criteria) this;
        }

        public Criteria andBeizhuEqualTo(String value) {
            addCriterion("Beizhu =", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuNotEqualTo(String value) {
            addCriterion("Beizhu <>", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuGreaterThan(String value) {
            addCriterion("Beizhu >", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuGreaterThanOrEqualTo(String value) {
            addCriterion("Beizhu >=", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuLessThan(String value) {
            addCriterion("Beizhu <", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuLessThanOrEqualTo(String value) {
            addCriterion("Beizhu <=", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuLike(String value) {
            addCriterion("Beizhu like", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuNotLike(String value) {
            addCriterion("Beizhu not like", value, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuIn(List<String> values) {
            addCriterion("Beizhu in", values, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuNotIn(List<String> values) {
            addCriterion("Beizhu not in", values, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuBetween(String value1, String value2) {
            addCriterion("Beizhu between", value1, value2, "beizhu");
            return (Criteria) this;
        }

        public Criteria andBeizhuNotBetween(String value1, String value2) {
            addCriterion("Beizhu not between", value1, value2, "beizhu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_user
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 23 16:23:24 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_user
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}