package com.hdy.myhxc.mapper;

import com.hdy.myhxc.model.RoleAuthority;
import com.hdy.myhxc.model.RoleAuthorityExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface RoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @SelectProvider(type=RoleAuthoritySqlProvider.class, method="countByExample")
    long countByExample(RoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @DeleteProvider(type=RoleAuthoritySqlProvider.class, method="deleteByExample")
    int deleteByExample(RoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @Delete({
        "delete from m_roleauthority",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @Insert({
        "insert into m_roleauthority (UUID, Role_UUID, ",
        "Menu_ID, Create_User, ",
        "Create_Date, Update_User, ",
        "Update_Date, DelFg, ",
        "Beizhu)",
        "values (#{uuid,jdbcType=VARCHAR}, #{roleUuid,jdbcType=VARCHAR}, ",
        "#{menuId,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{delfg,jdbcType=VARCHAR}, ",
        "#{beizhu,jdbcType=VARCHAR})"
    })
    int insert(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @InsertProvider(type=RoleAuthoritySqlProvider.class, method="insertSelective")
    int insertSelective(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @SelectProvider(type=RoleAuthoritySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="Role_UUID", property="roleUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Menu_ID", property="menuId", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_User", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_Date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Update_User", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Update_Date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DelFg", property="delfg", jdbcType=JdbcType.VARCHAR),
        @Result(column="Beizhu", property="beizhu", jdbcType=JdbcType.VARCHAR)
    })
    List<RoleAuthority> selectByExample(RoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @Select({
        "select",
        "UUID, Role_UUID, Menu_ID, Create_User, Create_Date, Update_User, Update_Date, ",
        "DelFg, Beizhu",
        "from m_roleauthority",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="Role_UUID", property="roleUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Menu_ID", property="menuId", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_User", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_Date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Update_User", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Update_Date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DelFg", property="delfg", jdbcType=JdbcType.VARCHAR),
        @Result(column="Beizhu", property="beizhu", jdbcType=JdbcType.VARCHAR)
    })
    RoleAuthority selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @UpdateProvider(type=RoleAuthoritySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") RoleAuthority record, @Param("example") RoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @UpdateProvider(type=RoleAuthoritySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") RoleAuthority record, @Param("example") RoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @UpdateProvider(type=RoleAuthoritySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @Update({
        "update m_roleauthority",
        "set Role_UUID = #{roleUuid,jdbcType=VARCHAR},",
          "Menu_ID = #{menuId,jdbcType=VARCHAR},",
          "Create_User = #{createUser,jdbcType=VARCHAR},",
          "Create_Date = #{createDate,jdbcType=TIMESTAMP},",
          "Update_User = #{updateUser,jdbcType=VARCHAR},",
          "Update_Date = #{updateDate,jdbcType=TIMESTAMP},",
          "DelFg = #{delfg,jdbcType=VARCHAR},",
          "Beizhu = #{beizhu,jdbcType=VARCHAR}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(RoleAuthority record);
}