package com.hdy.myhxc.mapper;

import com.hdy.myhxc.model.Roleauthority;
import com.hdy.myhxc.model.RoleauthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RoleauthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @SelectProvider(type=RoleauthoritySqlProvider.class, method="countByExample")
    long countByExample(RoleauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @DeleteProvider(type=RoleauthoritySqlProvider.class, method="deleteByExample")
    int deleteByExample(RoleauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @Delete({
        "delete from m_roleauthority",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @Insert({
        "insert into m_roleauthority (UUID, Role_UUID, ",
        "Menu_ID, Create_User, ",
        "Create_Date, Update_User, ",
        "Update_Date, DelFg, ",
        "Beizhu)",
        "values (#{uuid,jdbcType=VARCHAR}, #{roleUuid,jdbcType=VARCHAR}, ",
        "#{menuId,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{delfg,jdbcType=VARCHAR}, ",
        "#{beizhu,jdbcType=VARCHAR})"
    })
    int insert(Roleauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @InsertProvider(type=RoleauthoritySqlProvider.class, method="insertSelective")
    int insertSelective(Roleauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @SelectProvider(type=RoleauthoritySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="Role_UUID", property="roleUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Menu_ID", property="menuId", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_User", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_Date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Update_User", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Update_Date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DelFg", property="delfg", jdbcType=JdbcType.VARCHAR),
        @Result(column="Beizhu", property="beizhu", jdbcType=JdbcType.VARCHAR)
    })
    List<Roleauthority> selectByExample(RoleauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @Select({
        "select",
        "UUID, Role_UUID, Menu_ID, Create_User, Create_Date, Update_User, Update_Date, ",
        "DelFg, Beizhu",
        "from m_roleauthority",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="Role_UUID", property="roleUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Menu_ID", property="menuId", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_User", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_Date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Update_User", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Update_Date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DelFg", property="delfg", jdbcType=JdbcType.VARCHAR),
        @Result(column="Beizhu", property="beizhu", jdbcType=JdbcType.VARCHAR)
    })
    Roleauthority selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @UpdateProvider(type=RoleauthoritySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Roleauthority record, @Param("example") RoleauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @UpdateProvider(type=RoleauthoritySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Roleauthority record, @Param("example") RoleauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @UpdateProvider(type=RoleauthoritySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Roleauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_roleauthority
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @Update({
        "update m_roleauthority",
        "set Role_UUID = #{roleUuid,jdbcType=VARCHAR},",
          "Menu_ID = #{menuId,jdbcType=VARCHAR},",
          "Create_User = #{createUser,jdbcType=VARCHAR},",
          "Create_Date = #{createDate,jdbcType=TIMESTAMP},",
          "Update_User = #{updateUser,jdbcType=VARCHAR},",
          "Update_Date = #{updateDate,jdbcType=TIMESTAMP},",
          "DelFg = #{delfg,jdbcType=VARCHAR},",
          "Beizhu = #{beizhu,jdbcType=VARCHAR}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Roleauthority record);
}