package com.hdy.myhxc.mapper;

import com.hdy.myhxc.model.Userrole;
import com.hdy.myhxc.model.UserroleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @SelectProvider(type=UserroleSqlProvider.class, method="countByExample")
    long countByExample(UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @DeleteProvider(type=UserroleSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @Delete({
        "delete from m_userrole",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @Insert({
        "insert into m_userrole (UUID, User_UUID, ",
        "Role_UUID, Create_User, ",
        "Create_Data, Update_User, ",
        "Update_Date, DelFg, ",
        "Beizhu)",
        "values (#{uuid,jdbcType=VARCHAR}, #{userUuid,jdbcType=VARCHAR}, ",
        "#{roleUuid,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
        "#{createData,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{delfg,jdbcType=VARCHAR}, ",
        "#{beizhu,jdbcType=VARCHAR})"
    })
    int insert(Userrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @InsertProvider(type=UserroleSqlProvider.class, method="insertSelective")
    int insertSelective(Userrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @SelectProvider(type=UserroleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="User_UUID", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Role_UUID", property="roleUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_User", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_Data", property="createData", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Update_User", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Update_Date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DelFg", property="delfg", jdbcType=JdbcType.VARCHAR),
        @Result(column="Beizhu", property="beizhu", jdbcType=JdbcType.VARCHAR)
    })
    List<Userrole> selectByExample(UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @Select({
        "select",
        "UUID, User_UUID, Role_UUID, Create_User, Create_Data, Update_User, Update_Date, ",
        "DelFg, Beizhu",
        "from m_userrole",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="User_UUID", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Role_UUID", property="roleUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_User", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_Data", property="createData", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Update_User", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Update_Date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DelFg", property="delfg", jdbcType=JdbcType.VARCHAR),
        @Result(column="Beizhu", property="beizhu", jdbcType=JdbcType.VARCHAR)
    })
    Userrole selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @UpdateProvider(type=UserroleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Userrole record, @Param("example") UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @UpdateProvider(type=UserroleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Userrole record, @Param("example") UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @UpdateProvider(type=UserroleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Userrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @Update({
        "update m_userrole",
        "set User_UUID = #{userUuid,jdbcType=VARCHAR},",
          "Role_UUID = #{roleUuid,jdbcType=VARCHAR},",
          "Create_User = #{createUser,jdbcType=VARCHAR},",
          "Create_Data = #{createData,jdbcType=TIMESTAMP},",
          "Update_User = #{updateUser,jdbcType=VARCHAR},",
          "Update_Date = #{updateDate,jdbcType=TIMESTAMP},",
          "DelFg = #{delfg,jdbcType=VARCHAR},",
          "Beizhu = #{beizhu,jdbcType=VARCHAR}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Userrole record);
}