package com.hdy.myhxc.mapper;

import com.hdy.myhxc.model.Userdep;
import com.hdy.myhxc.model.UserdepExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserdepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @SelectProvider(type=UserdepSqlProvider.class, method="countByExample")
    long countByExample(UserdepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @DeleteProvider(type=UserdepSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserdepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @Delete({
        "delete from m_userdep",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @Insert({
        "insert into m_userdep (UUID, Dep_Name, ",
        "Dep_Level, Dep_TopID, ",
        "Dep_TopName, Show_Idx, ",
        "Create_User, Create_Date, ",
        "Update_User, Update_Date, ",
        "DelFg, Beizhu)",
        "values (#{uuid,jdbcType=VARCHAR}, #{depName,jdbcType=VARCHAR}, ",
        "#{depLevel,jdbcType=INTEGER}, #{depTopid,jdbcType=VARCHAR}, ",
        "#{depTopname,jdbcType=VARCHAR}, #{showIdx,jdbcType=INTEGER}, ",
        "#{createUser,jdbcType=VARCHAR}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{updateUser,jdbcType=VARCHAR}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{delfg,jdbcType=VARCHAR}, #{beizhu,jdbcType=VARCHAR})"
    })
    int insert(Userdep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @InsertProvider(type=UserdepSqlProvider.class, method="insertSelective")
    int insertSelective(Userdep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @SelectProvider(type=UserdepSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="Dep_Name", property="depName", jdbcType=JdbcType.VARCHAR),
        @Result(column="Dep_Level", property="depLevel", jdbcType=JdbcType.INTEGER),
        @Result(column="Dep_TopID", property="depTopid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Dep_TopName", property="depTopname", jdbcType=JdbcType.VARCHAR),
        @Result(column="Show_Idx", property="showIdx", jdbcType=JdbcType.INTEGER),
        @Result(column="Create_User", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_Date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Update_User", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Update_Date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DelFg", property="delfg", jdbcType=JdbcType.VARCHAR),
        @Result(column="Beizhu", property="beizhu", jdbcType=JdbcType.VARCHAR)
    })
    List<Userdep> selectByExample(UserdepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @Select({
        "select",
        "UUID, Dep_Name, Dep_Level, Dep_TopID, Dep_TopName, Show_Idx, Create_User, Create_Date, ",
        "Update_User, Update_Date, DelFg, Beizhu",
        "from m_userdep",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="Dep_Name", property="depName", jdbcType=JdbcType.VARCHAR),
        @Result(column="Dep_Level", property="depLevel", jdbcType=JdbcType.INTEGER),
        @Result(column="Dep_TopID", property="depTopid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Dep_TopName", property="depTopname", jdbcType=JdbcType.VARCHAR),
        @Result(column="Show_Idx", property="showIdx", jdbcType=JdbcType.INTEGER),
        @Result(column="Create_User", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_Date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Update_User", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Update_Date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DelFg", property="delfg", jdbcType=JdbcType.VARCHAR),
        @Result(column="Beizhu", property="beizhu", jdbcType=JdbcType.VARCHAR)
    })
    Userdep selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @UpdateProvider(type=UserdepSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Userdep record, @Param("example") UserdepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @UpdateProvider(type=UserdepSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Userdep record, @Param("example") UserdepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @UpdateProvider(type=UserdepSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Userdep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userdep
     *
     * @mbg.generated Fri Aug 23 16:23:24 CST 2019
     */
    @Update({
        "update m_userdep",
        "set Dep_Name = #{depName,jdbcType=VARCHAR},",
          "Dep_Level = #{depLevel,jdbcType=INTEGER},",
          "Dep_TopID = #{depTopid,jdbcType=VARCHAR},",
          "Dep_TopName = #{depTopname,jdbcType=VARCHAR},",
          "Show_Idx = #{showIdx,jdbcType=INTEGER},",
          "Create_User = #{createUser,jdbcType=VARCHAR},",
          "Create_Date = #{createDate,jdbcType=TIMESTAMP},",
          "Update_User = #{updateUser,jdbcType=VARCHAR},",
          "Update_Date = #{updateDate,jdbcType=TIMESTAMP},",
          "DelFg = #{delfg,jdbcType=VARCHAR},",
          "Beizhu = #{beizhu,jdbcType=VARCHAR}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Userdep record);
}