package com.hdy.myhxc.mapper;

import com.hdy.myhxc.model.UserRole;
import com.hdy.myhxc.model.UserRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @SelectProvider(type=UserRoleSqlProvider.class, method="countByExample")
    long countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @DeleteProvider(type=UserRoleSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @Delete({
        "delete from m_userrole",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @Insert({
        "insert into m_userrole (UUID, User_UUID, ",
        "Role_UUID, Create_User, ",
        "Create_Data, Update_User, ",
        "Update_Date, DelFg, ",
        "Beizhu)",
        "values (#{uuid,jdbcType=VARCHAR}, #{userUuid,jdbcType=VARCHAR}, ",
        "#{roleUuid,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
        "#{createData,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{delfg,jdbcType=VARCHAR}, ",
        "#{beizhu,jdbcType=VARCHAR})"
    })
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @InsertProvider(type=UserRoleSqlProvider.class, method="insertSelective")
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @SelectProvider(type=UserRoleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="User_UUID", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Role_UUID", property="roleUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_User", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_Data", property="createData", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Update_User", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Update_Date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DelFg", property="delfg", jdbcType=JdbcType.VARCHAR),
        @Result(column="Beizhu", property="beizhu", jdbcType=JdbcType.VARCHAR)
    })
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @Select({
        "select",
        "UUID, User_UUID, Role_UUID, Create_User, Create_Data, Update_User, Update_Date, ",
        "DelFg, Beizhu",
        "from m_userrole",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="User_UUID", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Role_UUID", property="roleUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_User", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Create_Data", property="createData", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Update_User", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="Update_Date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DelFg", property="delfg", jdbcType=JdbcType.VARCHAR),
        @Result(column="Beizhu", property="beizhu", jdbcType=JdbcType.VARCHAR)
    })
    UserRole selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @UpdateProvider(type=UserRoleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @UpdateProvider(type=UserRoleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @UpdateProvider(type=UserRoleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_userrole
     *
     * @mbg.generated Mon Aug 26 14:48:07 CST 2019
     */
    @Update({
        "update m_userrole",
        "set User_UUID = #{userUuid,jdbcType=VARCHAR},",
          "Role_UUID = #{roleUuid,jdbcType=VARCHAR},",
          "Create_User = #{createUser,jdbcType=VARCHAR},",
          "Create_Data = #{createData,jdbcType=TIMESTAMP},",
          "Update_User = #{updateUser,jdbcType=VARCHAR},",
          "Update_Date = #{updateDate,jdbcType=TIMESTAMP},",
          "DelFg = #{delfg,jdbcType=VARCHAR},",
          "Beizhu = #{beizhu,jdbcType=VARCHAR}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(UserRole record);
}